version: "3.9"
services:
  mongo:
    image: mongo:6
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

  user_service:
    build: ./user_service
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongo:27017
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - app_network

  court_service:
    build: ./court_service
    ports:
      - "8001:8001"
    environment:
      - MONGODB_URL=mongodb://mongo:27017
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - app_network

  booking_service:
    build: ./booking_service
    ports:
      - "8002:8002"
    environment:
      - MONGODB_URL=mongodb://mongo:27017
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - app_network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - booking_service
    networks:
      - app_network

volumes:
  mongo_data:

networks:
  app_network:
    driver: bridge