version: '3.8'

services:
  # Lightweight MongoDB for testing
  mongo-booking:
    image: mongo:7.0-jammy
    container_name: tennisinaja-mongo-booking-test
    restart: always
    ports:
      - "27019:27017"
    environment:
      - MONGO_INITDB_DATABASE=tennisinaja_bookings
    # Remove healthcheck to speed up startup
    # networks:
    #   - booking-network

  booking_service:
    build:
      context: ./booking_service
    container_name: tennisinaja-booking-test
    environment:
      - MONGODB_URL=mongodb://mongo-booking:27017
      - SECRET_KEY=supersecretkey
    depends_on:
      - mongo-booking
    ports:
      - "8002:8002"
    restart: unless-stopped

# Remove networks to simplify
# networks:
#   booking-network:
#     driver: bridge
