version: '3.8'

services:
  mongo-court:
    image: mongo:7.0
    container_name: mongo-court
    ports:
      - "27017:27017"
    volumes:
      - mongo_court_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: tennisinaja_courts
    restart: unless-stopped

  court_service:
    build: ./court_service
    container_name: court_service
    ports:
      - "8001:8001"
    environment:
      - MONGODB_URL=mongodb://mongo-court:27017
    depends_on:
      - mongo-court
    restart: unless-stopped

volumes:
  mongo_court_data:
