version: "3.9"
services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  user_service:
    build: ./user_service
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongo:27017
    depends_on:
      - mongo

  court_service:
    build: ./court_service
    ports:
      - "8001:8001"
    environment:
      - MONGODB_URL=mongodb://mongo:27017
    depends_on:
      - mongo

  booking_service:
    build: ./booking_service
    ports:
      - "8002:8002"
    environment:
      - MONGODB_URL=mongodb://mongo:27017
    depends_on:
      - mongo

volumes:
  mongo_data: